name: Tests
on:
  pull_request:

env:
  QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
jobs:
  local-tests:
    runs-on: ubuntu-latest

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint
        run: bun run fmt

      - name: Run tests
        run: bun test --bail

      - name: Build
        run: bun run build

  cloudflare-workers-local-build:
    runs-on: ubuntu-latest
    needs: local-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: true

      - name: Local build
        run: pnpm run start
        working-directory: examples/cloudflare-workers
