name: Tests
on:
  pull_request:

env:
  QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
jobs:
  test:
    runs-on:
      group: large-runners
      labels: ubuntu-4x
    concurrency: test

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint
        run: bun run fmt

      - name: Run tests
        run: bun test pkg --bail --timeout 20000

      - name: Build
        run: bun run build

  cloudflare-workers-local-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install example
        run: pnpm install
        working-directory: examples/cloudflare-workers

      - name: Local build
        run: pnpm run start
        working-directory: examples/cloudflare-workers
